# -*- coding: utf-8 -*-
"""Final Malaria Paper Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOGTMMP8PZpas01YfgyZDcaY6zXn8bXG

## General Model
"""

import numpy as np
from scipy.integrate import simpson


class AgeStructuredModel:
    """Base class. Subclasses override reaction, birth_kernel,
    initial_condition. For q > 0, also override reaction_ode and initial_ode."""

    def reaction(self, t, ages, u, w):
        """Return f(t, a, u, w), shape (d, M)."""
        raise NotImplementedError

    def birth_kernel(self, ages, u):
        """Return B(a) u, shape (d, M). Integrated over ages to give u(t, 0)."""
        raise NotImplementedError

    def initial_condition(self, ages):
        """Return u_0(a), shape (d, M)."""
        raise NotImplementedError

    def reaction_ode(self, t, u, w):
        """Return g(t, u, w), shape (q,). Default: q = 0."""
        return np.zeros(0)

    def initial_ode(self):
        """Return w_0, shape (q,). Default: q = 0."""
        return np.zeros(0)


class AgeStructuredSolver:

    def __init__(self, model, A_max, M):
        self.model = model
        self.A_max = float(A_max)
        self.M     = int(M)

        self.ages = np.linspace(0.0, self.A_max, self.M)
        self.da   = self.ages[1] - self.ages[0]
        self.dt   = self.da

        u0 = np.asarray(model.initial_condition(self.ages), dtype=float)
        if u0.ndim == 1:
            u0 = u0.reshape(1, -1)
        self.u = u0.copy()
        self.d = self.u.shape[0]

        self.w = np.asarray(model.initial_ode(), dtype=float).copy()
        self.q = self.w.size

        self.t = 0.0

    def _reaction_substep(self, dt, t_start):
        u, w = self.u, self.w
        k1_u = self.model.reaction    (t_start, self.ages, u, w)
        k1_w = self.model.reaction_ode(t_start,            u, w)

        u_pred = u + dt * k1_u
        w_pred = w + dt * k1_w

        k2_u = self.model.reaction    (t_start + dt, self.ages, u_pred, w_pred)
        k2_w = self.model.reaction_ode(t_start + dt,            u_pred, w_pred)

        self.u = u + 0.5 * dt * (k1_u + k2_u)
        self.w = w + 0.5 * dt * (k1_w + k2_w)

    def _transport_substep(self):
        prev_u0      = self.u[:, 0].copy()
        self.u       = np.roll(self.u, 1, axis=1)
        self.u[:, 0] = prev_u0

    def _apply_boundary(self):
        integrand               = self.model.birth_kernel(self.ages, self.u)
        integrand_no_a0         = integrand.copy()
        integrand_no_a0[:, 0]   = 0.0
        partial_integral        = simpson(integrand_no_a0, x=self.ages, axis=1)
        self.u[:, 0]            = partial_integral + (self.da / 3.0) * integrand[:, 0]

    def step(self):
        t0 = self.t
        self._reaction_substep(self.dt / 2.0, t_start=t0)
        self._transport_substep()
        self._reaction_substep(self.dt / 2.0, t_start=t0 + self.dt / 2.0)
        self._apply_boundary()
        self.t = t0 + self.dt

    def run(self, T, callback=None):
        n_steps = int(round(T / self.dt))
        for _ in range(n_steps):
            self.step()
            if callback is not None:
                callback(self.t, self.u, self.w)
        return self.u, self.w

"""## Toy Problem"""

"""
Example: Gurtin-MacCamy model implemented via AgeStructuredModel.

Uses the smooth rates from Milner & Rabbiolo (1992) Section 5 and verifies
that the general solver achieves second-order convergence on the analytical
steady-state test.
"""
import numpy as np
from scipy.integrate import trapezoid


# --- Rate functions (Milner & Rabbiolo Section 5) -----------------------
def f_bump(x):
    x = np.asarray(x, dtype=float)
    out = np.zeros_like(x)
    m = x > 1e-12
    out[m] = np.exp(-((1.0 - x[m]) / x[m]) ** 2)
    return out

def mu_age(a):
    a   = np.asarray(a, dtype=float)
    out = np.full_like(a, 12.0)
    m   = (a >= 0) & (a <= 85)
    out[m] = 12.0 * f_bump(a[m] / 85.0)
    return out

def beta_shape(a):
    a   = np.asarray(a, dtype=float)
    out = np.zeros_like(a)
    m   = (a >= 15) & (a <= 45)
    out[m] = f_bump(1.0 - np.abs(a[m] - 30.0) / 15.0)
    return out

# Normalize beta so that the steady state phi(a) = b0 * exp(-int mu) is a fixed point.
_ages_ref = np.linspace(0.0, 200.0, 200_001)
_mu_ref   = mu_age(_ages_ref)
_cumint   = np.concatenate(([0.0],
    np.cumsum(0.5 * (_mu_ref[:-1] + _mu_ref[1:]) * np.diff(_ages_ref))))
_surv     = np.exp(-_cumint)
K_NORM    = trapezoid(beta_shape(_ages_ref) * _surv, x=_ages_ref)

def beta_age(a):    return beta_shape(a) / K_NORM
def survival(a):    return np.interp(a, _ages_ref, _surv)
def phi_steady(a):  return 1.0e5 * survival(a)


# --- The model, expressed in the framework -----------------------------
class GurtinMacCamy(AgeStructuredModel):
    """Scalar (d=1) age-structured model with age-dependent mortality
    and renewal boundary."""

    def reaction(self, t, ages, u, w):
        return -mu_age(ages) * u                       # shape (1, M)

    def birth_kernel(self, ages, u):
        return (beta_age(ages) * u).reshape(1, -1)     # shape (1, M)

    def initial_condition(self, ages):
        return phi_steady(ages).reshape(1, -1)         # shape (1, M)


# --- Convergence verification ------------------------------------------
def run_one(dt, T=10.0, A_max=100.0):
    M = int(round(A_max / dt)) + 1
    solver = AgeStructuredSolver(GurtinMacCamy(), A_max=A_max, M=M)
    phi_grid = phi_steady(solver.ages).reshape(1, -1)

    n_steps = int(round(T / solver.dt))
    max_err = 0.0
    for _ in range(n_steps):
        solver.step()
        err = float(np.max(np.abs(solver.u - phi_grid)))
        if err > max_err:
            max_err = err
    return max_err


if __name__ == '__main__':
    print(f"k = {K_NORM:.6f}    (paper reports ~ 5.854)\n")
    print(f"{'dt':>10}  {'E(dt)':>16}  {'r(dt)':>10}")
    print("-" * 42)

    dts  = [1/6, 1/12, 1/24, 1/48]
    errs = [run_one(dt) for dt in dts]

    for i, dt in enumerate(dts):
        if i < len(dts) - 1:
            r = np.log(errs[i] / errs[i + 1]) / np.log(2.0)
            print(f"{dt:>10.5f}  {errs[i]:>16.6e}  {r:>10.4f}")
        else:
            print(f"{dt:>10.5f}  {errs[i]:>16.6e}  {'-':>10}")

"""## Malaria"""

"""Parameter functions for the Kawakami-Zhao (2021) malaria model."""

import numpy as np

A_MAX = 90.0

# --- Demographic --------------------------------------------------------

def b_h(a, c=1.1644):
    """Birth rate. Brass form fit to Nigeria 2015 data.
    The constant c is rescaled from Kawakami's 0.4496 to give a self-consistent
    disease-free equilibrium at N_h* ~ 10^8 with the density-dependent
    mortality mu_h1 * N_h."""
    b1, b2, b3, b4 = 0.0001218, 0.3022, 78.38, 0.04006
    a = np.asarray(a, dtype=float)
    return c * b1 * np.exp(-b2 * (a - b3) - np.exp(-b4 * (a - b3)))

def mu_h0(a):
    """Age-only mortality (Heligman-Pollard form). The mu_o term diverges
    as a -> A; we cap it at a finite value so the stiffness stays bounded."""
    a = np.asarray(a, dtype=float)
    mu_c = 0.9959 * np.exp(-0.6776 * a)
    mu_m = 0.1277 * np.exp(0.09171 * (a - 66.78)
                           - np.exp(0.0006743 * (a - 66.78)))
    denom = np.maximum(A_MAX - a, 0.5)
    mu_o = 0.05859 / denom
    return mu_c + mu_m + mu_o

MU_H1 = 1.6e-10

def mu_h(a, N_h):
    return mu_h0(a) + MU_H1 * N_h

# --- Disease ------------------------------------------------------------

def rho(a):
    """Biting preference (sigmoidal in age)."""
    a = np.asarray(a, dtype=float)
    return 1.0 / (1.0 + np.exp(-(a - 4.0))) - 1.0 / (1.0 + np.exp(4.0))

def delta_h(a, c=0.006444):
    """Malaria-induced mortality (high in 0-5, ~0 elsewhere)."""
    a = np.asarray(a, dtype=float)
    return c / (1.0 + np.exp(2.0 * a - 14.0))

ZETA_H  = 1.0
GAMMA_H = 2.0

# --- Mosquito -----------------------------------------------------------

LAMBDA_V = 1.0e10
MU_V     = 13.0

# --- Transmission -------------------------------------------------------

BETA_BASELINE = 18.0
P1            = 0.5
P2            = 2.0 / 45.0

"""Kawakami-Zhao (2021) malaria model as an AgeStructuredModel.

State layout:
    u[0] = s_h(t, a)   (susceptible hosts)
    u[1] = i_h(t, a)   (infected hosts)
    u[2] = r_h(t, a)   (recovered hosts)
    w[0] = S_v(t)      (susceptible mosquitoes)
    w[1] = I_v(t)      (infected mosquitoes)
"""

import numpy as np
from scipy.integrate import trapezoid



class KawakamiMalaria(AgeStructuredModel):

    def __init__(self, beta=BETA_BASELINE,
                 s_init_total=1.0e8, i_init_frac=1.0e-3, ages_for_init=None):
        self.beta         = beta
        self.s_init_total = s_init_total
        self.i_init_frac  = i_init_frac
        self._ages_init   = ages_for_init        # optional; for IC shape

    def reaction(self, t, ages, u, w):
        s_h, i_h, r_h = u[0], u[1], u[2]
        S_v, I_v      = w[0], w[1]

        n_h          = s_h + i_h + r_h
        N_h          = trapezoid(n_h, x=ages)
        rho_vals     = rho(ages)
        rho_n_int    = trapezoid(rho_vals * n_h, x=ages)
        rho_n_int    = max(rho_n_int, 1e-30)

        lambda_vh    = P1 * self.beta * I_v * rho_vals / rho_n_int
        mu_h_L         = mu_h(ages, N_h)
        delta_h_vals = delta_h(ages)

        du = np.empty_like(u)
        du[0] = -lambda_vh * s_h + GAMMA_H * r_h - mu_h_L * s_h
        du[1] =  lambda_vh * s_h - (ZETA_H + delta_h_vals + mu_h_L) * i_h
        du[2] =  ZETA_H * i_h - (GAMMA_H + mu_h_L) * r_h
        return du

    def reaction_ode(self, t, u, w):
        s_h, i_h, r_h = u[0], u[1], u[2]
        S_v, I_v      = w[0], w[1]

        ages         = self._ages_cache
        n_h          = s_h + i_h + r_h
        rho_vals     = rho(ages)
        rho_n_int    = trapezoid(rho_vals * n_h, x=ages)
        rho_n_int    = max(rho_n_int, 1e-30)
        rho_i_int    = trapezoid(rho_vals * i_h, x=ages)

        lambda_hv    = P2 * self.beta * rho_i_int / rho_n_int

        dw = np.empty(2)
        dw[0] = LAMBDA_V - (lambda_hv + MU_V) * S_v
        dw[1] = lambda_hv * S_v - MU_V * I_v
        return dw

    def birth_kernel(self, ages, u):
        """All births enter s_h. Birth rate b_h(a) acts on total n_h."""
        n_h    = u[0] + u[1] + u[2]
        out    = np.zeros_like(u)
        out[0] = b_h(ages) * n_h
        return out

    def initial_condition(self, ages):
        """Set susceptible-only IC scaled to s_init_total, plus small i seed."""
        self._ages_cache = ages
        # Approximate susceptible age profile by survival under mu_h0.
        cumint   = np.concatenate(([0.0],
            np.cumsum(0.5*(mu_h0(ages[:-1]) + mu_h0(ages[1:])) * np.diff(ages))))
        surv     = np.exp(-cumint)
        scale    = self.s_init_total / max(trapezoid(surv, x=ages), 1e-30)
        s0       = scale * surv
        i0       = self.i_init_frac * s0

        u0 = np.zeros((3, ages.size))
        u0[0] = s0 - i0
        u0[1] = i0
        u0[2] = 0.0
        return u0

    def initial_ode(self):
        S_v0 = LAMBDA_V / MU_V
        I_v0 = self.i_init_frac * S_v0
        return np.array([S_v0, I_v0])

"""Disease-free equilibrium computation and Kawakami's R_0 formula."""

import numpy as np
from scipy.integrate import trapezoid


def compute_dfe(M, T_settle=300.0, s_init_total=1.0e8):
    """Run the disease-free model to steady state. Returns (ages, s_star, N_star, S_v_star)."""
    model  = KawakamiMalaria(beta=1.0, s_init_total=s_init_total, i_init_frac=0.0)
    solver = AgeStructuredSolver(model, A_max=A_MAX, M=M)
    solver.run(T=T_settle)
    ages    = solver.ages
    s_star  = solver.u[0]
    N_star  = float(trapezoid(s_star, x=ages))
    S_v_star = float(solver.w[0])
    return ages, s_star, N_star, S_v_star


def R0(beta, ages, s_star, N_star):
    """Evaluate Kawakami's formula

        R_0 = integral_0^A R_1(sigma) R_2(sigma) d sigma,

        R_1(sigma) = p_1 beta rho(sigma) s*(sigma) / (rho_n_int * mu_v)
        R_2(sigma) = integral_sigma^A [p_2 beta rho(a) Lambda_v / (rho_n_int mu_v)]
                        * exp(-int_sigma^a [zeta + delta + mu_h] db) da
    """
    rho_vals     = rho(ages)
    rho_n_int    = trapezoid(rho_vals * s_star, x=ages)   # n* = s* at DFE
    mu_h_star    = mu_h(ages, N_star)
    leave_rate   = ZETA_H + delta_h(ages) + mu_h_star

    # cumulative integral of leave_rate (trapezoidal)
    cum_leave    = np.concatenate(([0.0],
        np.cumsum(0.5 * (leave_rate[:-1] + leave_rate[1:]) * np.diff(ages))))

    R1 = P1 * beta * rho_vals * s_star / (rho_n_int * MU_V)

    R2_integrand = P2 * beta * rho_vals * LAMBDA_V / (rho_n_int * MU_V)
    # For each sigma, R_2(sigma) = int_sigma^A R2_integrand(a) * exp(-(cum_leave[a] - cum_leave[sigma])) da
    R2 = np.empty_like(ages)
    for i in range(len(ages)):
        kernel = R2_integrand[i:] * np.exp(-(cum_leave[i:] - cum_leave[i]))
        R2[i]  = trapezoid(kernel, x=ages[i:]) if i < len(ages) - 1 else 0.0

    return float(trapezoid(R1 * R2, x=ages))


def beta_critical(ages, s_star, N_star, beta_ref=1.0):
    """R_0 scales as beta^2, so beta* = beta_ref / sqrt(R_0(beta_ref))."""
    R0_ref = R0(beta_ref, ages, s_star, N_star)
    return beta_ref / np.sqrt(R0_ref)

"""Section 6 experiments: verify R_0 for the Kawakami malaria model.

Three results, in order:
  1. DFE verification        -- simulated DFE matches the analytical DFE
  2. Threshold figure        -- 0.99*beta* decays, 1.01*beta* persists
  3. Sensitivity sweep table -- six beta values, R_0 from formula, outcome
"""

import time
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import trapezoid


M       = 1801
A_MAX   = A_MAX
T_LONG  = 500.0
EPSILON = 1.0e-3


# ---------------------------------------------------------------------
# Result 1: DFE verification
# ---------------------------------------------------------------------
def result_1_dfe_verification():
    print("=== Result 1: DFE verification ===")
    ages, s_star, N_star, S_v_star = compute_dfe(M=M, T_settle=300.0)

    # Analytical DFE: s*(a) = s*(0) exp(-int_0^a [mu_h0 + mu_h1 N*]).
    # Use the simulated N* in the exponent for a self-consistent comparison.
    cumint = np.concatenate(([0.0],
        np.cumsum(0.5 * (mu_h0(ages[:-1]) + mu_h0(ages[1:])) * np.diff(ages))))
    surv_analytic = np.exp(-cumint - MU_H1 * N_star * ages)
    s_star_analytic = s_star[0] * surv_analytic / surv_analytic[0]

    rel_err = np.max(np.abs(s_star - s_star_analytic)) / s_star[0]
    print(f"  N_h^*               = {N_star:.4e}")
    print(f"  S_v^*               = {S_v_star:.4e}")
    print(f"  max |s_sim - s_an|  = {rel_err:.2e} (relative to s*(0))")
    print()
    return ages, s_star, N_star, S_v_star


# ---------------------------------------------------------------------
# Result 2: threshold figure
# ---------------------------------------------------------------------
def result_2_threshold_figure(ages, s_star, N_star):
    print("=== Result 2: threshold figure ===")
    beta_star = beta_critical(ages, s_star, N_star)
    print(f"  beta* = {beta_star:.4f}    (from formula)")

    factors = [0.99, 1.01]
    histories = {}

    for factor in factors:
        beta_used = factor * beta_star
        R_used    = R0(beta_used, ages, s_star, N_star)
        print(f"  running beta = {factor}*beta* = {beta_used:.4f}, R_0 = {R_used:.5f}")

        model  = KawakamiMalaria(beta=beta_used, i_init_frac=EPSILON)
        solver = AgeStructuredSolver(model, A_max=A_MAX, M=M)

        sample_every = int(round(0.5 / solver.dt))    # half-yearly samples
        ts, Ihs = [], []
        n_steps = int(round(T_LONG / solver.dt))
        t0 = time.perf_counter()
        for k in range(n_steps):
            solver.step()
            if (k + 1) % sample_every == 0:
                ts .append(solver.t)
                Ihs.append(trapezoid(solver.u[1], x=solver.ages))
        elapsed = time.perf_counter() - t0
        histories[factor] = (np.array(ts), np.array(Ihs), R_used, elapsed)
        print(f"    finished in {elapsed:.1f}s")

    # Figure
    fig, ax = plt.subplots(figsize=(7.0, 4.5))
    for factor, (ts, Ihs, R, _) in histories.items():
        label = (rf'$\beta = {factor}\,\beta^*$, $R_0 = {R:.3f}$')
        ax.plot(ts, Ihs, label=label, linewidth=1.5)
    ax.set_xlabel('time (years)')
    ax.set_ylabel(r'total infected hosts $I_h(t)$')
    ax.set_title(r'Threshold dichotomy near $R_0 = 1$')
    ax.legend(loc='upper right')
    ax.set_yscale('log')
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig('threshold_figure.pdf', bbox_inches='tight')
    fig.savefig('threshold_figure.png', dpi=150, bbox_inches='tight')
    print(f"  figure saved to threshold_figure.{{pdf,png}}")
    print()
    return beta_star


# ---------------------------------------------------------------------
# Result 3: sensitivity sweep
# ---------------------------------------------------------------------
def result_3_sweep_table(ages, s_star, N_star, beta_star):
    print("=== Result 3: sensitivity sweep ===")
    factors = [0.5, 0.95, 0.99, 1.01, 1.05, 2.0]
    rows    = []

    print(f"  {'factor':>7}  {'beta':>9}  {'R_0':>9}  {'final I_h':>12}  {'prev':>9}  {'outcome':>9}  {'time':>6}")
    print(f"  {'-'*7}  {'-'*9}  {'-'*9}  {'-'*12}  {'-'*9}  {'-'*9}  {'-'*6}")

    for factor in factors:
        beta_used = factor * beta_star
        R_used    = R0(beta_used, ages, s_star, N_star)

        model  = KawakamiMalaria(beta=beta_used, i_init_frac=EPSILON)
        solver = AgeStructuredSolver(model, A_max=A_MAX, M=M)
        t0 = time.perf_counter()
        solver.run(T=T_LONG)
        elapsed = time.perf_counter() - t0

        N_h = float(trapezoid(solver.u[0] + solver.u[1] + solver.u[2], x=solver.ages))
        I_h = float(trapezoid(solver.u[1], x=solver.ages))
        prev = I_h / N_h
        outcome = 'persist' if prev > 1e-4 else 'die-off'

        print(f"  {factor:>7.2f}  {beta_used:>9.4f}  {R_used:>9.5f}  "
              f"{I_h:>12.3e}  {prev*100:>8.4f}%  {outcome:>9}  {elapsed:>5.1f}s")
        rows.append((factor, beta_used, R_used, I_h, prev, outcome, elapsed))
    print()
    return rows


# ---------------------------------------------------------------------
def main():
    print(f"Grid: M = {M}, dt = {A_MAX/(M-1):.5f} yr, T = {T_LONG} yr\n")
    t_total = time.perf_counter()
    ages, s_star, N_star, S_v_star = result_1_dfe_verification()
    beta_star                       = result_2_threshold_figure(ages, s_star, N_star)
    rows                            = result_3_sweep_table(ages, s_star, N_star, beta_star)
    print(f"Total wall-clock: {time.perf_counter() - t_total:.1f}s")


if __name__ == '__main__':
    main()
